disabled_rules: # rule identifiers to exclude from running
  - line_length
  - trailing_whitespace
  - type_body_length
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle)
variable_name:
  max_length:
    warning: 45
    error: 60
  min_length:
    warning: 1
